app = "cloud-trader"
primary_region = "jnb"

[build]

[env]
FLASK_ENV = "production"

[http_service]
  internal_port = 5000
  force_https = true

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
